name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        node --version
        cd test-build
        npm install
        npm run build
       
    # Cache local node_modules to pass to testing jobs
    - name: Cache local node_modules
      id: cache_node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-node-modules-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}-   
        
    # Restore just local node_modules and the Cypress binary archives.
    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}-${{ github.ref }}
        restore-keys: |
          cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}-

